name: ClientNest Security Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    name: Run Security Scans
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-nest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- ESLint (JS/TS) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js deps
        run: npm install

      - name: Run ESLint
        run: |
          npm install -g eslint eslint-plugin-security
          eslint . --ext .js,.ts
          npm install --save-dev eslint eslint-plugin-security
          npx eslint . --ext .js,.ts

      # --- Bandit (Python) ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r ./backend

      # --- Semgrep ---
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config=auto .

      # --- OWASP Dependency-Check ---
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "ClientNest"
          path: "./client-nest"
          format: "HTML"
          out: "reports"

      # --- Upload HTML Report ---
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
